version: 1
filters:
    access_filter:
        (): sanic.defaultFilter.DefaultFilter
        param: [0, 10, 20]
    error_filter:
        (): sanic.defaultFilter.DefaultFilter
        param: [30, 40, 50]

formatters:
    simple:
        format: '%(asctime)s - (%(name)s)[%(levelname)s]: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    access:
        format: '%(asctime)s - [%(levelname)s][%(host)s]: %(request)s %(message)s %(status)s %(byte)d'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    internal:
        class: logging.handlers.TimedRotatingFileHandler
        filters: [access_filter]
        formatter: simple
        when: 'D'
        interval: 1
        backupCount: 7
        filename: 'access.log'

    access:
        class: logging.handlers.TimedRotatingFileHandler
        filters: [access_filter]
        formatter: access
        when: 'D'
        interval: 1
        backupCount: 7
        filename: 'access.log'

    error:
        class: logging.handlers.TimedRotatingFileHandler
        filters: [error_filter]
        filename: 'error.log'
        when: 'D'
        interval: 1
        backupCount: 7
        formatter: simple

loggers:
    sanic:
        level: DEBUG
        handlers: [internal, error]
    network:
        level: DEBUG
        handlers: [access, error]
